In [1]:
# Импортируйте библиотеку nympy
import numpy as np

def get_arr_props(arr):
    props = ['shape', 'ndim', 'dtype', 'nbytes', 'size', 'strides']
    return {prop: getattr(arr, prop) for prop in props if hasattr(arr, prop)}

In [2]:
# Создайте массив-скаляр (0D) со значением 5 и выведите его shape, ndim, dtype и nbytes.
# используйте np.array
print(get_arr_props(np.array(7)))

{'shape': (), 'ndim': 0, 'dtype': dtype('int64'), 'nbytes': 8, 'size': 1, 'strides': ()}


In [3]:
# Создайте одномерный нулевой вектор длиной 10 и выведите shape, ndim, dtype, nbytes.
# используйте np.zeros(10)
print(get_arr_props(np.zeros(10)))

{'shape': (10,), 'ndim': 1, 'dtype': dtype('float64'), 'nbytes': 80, 'size': 10, 'strides': (8,)}


In [4]:
# Создайте вектор со значениями от 10 до 49 включительно и выведите shape, ndim, dtype, size.
# используйте np.arange(10, 50)
print(get_arr_props(np.arange(10, 50)))

{'shape': (40,), 'ndim': 1, 'dtype': dtype('int64'), 'nbytes': 320, 'size': 40, 'strides': (8,)}


In [5]:
# Инвертируйте порядок элементов вектора из части 3 (первый элемент становится последним).
# используйте срез [::-1]
print(np.arange(10, 50)[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# Создайте матрицу 3x3 со значениями от 0 до 8.
# используйте np.arange(...).reshape(...)
print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Найдите индексы ненулевых элементов в массиве [1, 2, 0, 0, 4, 0].
# используйте np.nonzero(...)
print(np.nonzero(np.array([1, 2, 0, 0, 4, 0]))[0])

[0 1 4]


In [14]:
# Создайте массив 3x3x3 со случайными значениями и выведите shape, ndim, size.
# используйте np.random.rand(3, 3, 3)
print(get_arr_props(np.random.rand(3, 3, 3)))

{'shape': (3, 3, 3), 'ndim': 3, 'dtype': dtype('float64'), 'nbytes': 216, 'size': 27, 'strides': (72, 24, 8)}


In [25]:
# Создайте массив 10x10 со случайными значениями и найдите в нём min и max.
# используйте np.random.rand(10, 10), np.min(...), np.max(...)
print(np.min(arr:=np.random.rand(10, 10)), np.max(arr))

0.007142198910771613 0.9851628137018318


In [134]:
# Создайте случайный вектор размера 30 и найдите его среднее значение.
# используйте np.random.rand(...) и np.mean(...)
print(np.mean(arr:=np.random.rand(30)), arr.size, "\n", arr, "\n")
print(np.mean(arr:=np.random.randint(1, 10, 30_000)), arr.size, "\n", arr)   # запись числа с _ 30_000, при увеличении повторений случайное среднее стремится к среднему 1 до 9 тоетсь 5

0.5139455883147243 30 
 [0.19484651 0.52715058 0.92837651 0.64418769 0.25040143 0.32425052
 0.4475652  0.73642278 0.12557144 0.57906591 0.07464316 0.35101733
 0.79703115 0.96214183 0.93602255 0.39815142 0.82414093 0.55213404
 0.05776442 0.05239073 0.23873746 0.735006   0.29223771 0.92290037
 0.70391333 0.96233744 0.81213869 0.40957677 0.39535652 0.18288723] 

4.9978 30000 
 [6 5 2 ... 5 1 3]


In [94]:
# Создайте массив 3x3 с единицами по границе и нулями внутри.
# используйте np.ones(...) и срез a[1:-1, 1:-1] = 0                                                # однострочники
print((a := np.pad(np.zeros((1,1)), pad_width=1, constant_values=1)),'\n')                         # через моржа с pad   
print(exec('(a := np.ones((3,3)))[1:-1, 1:-1] = 0') or a,'\n')                                     # через exec() - как в условии
print(a := np.ones((3,3)).__setitem__((slice(1,-1), slice(1,-1)), 0) or a,'\n')                    # присвоение напрямую через __setitem__
print((lambda a: (a.__setitem__((slice(1,-1), slice(1,-1)), 0)) or a)(np.ones((3,3))),'\n')        # через lambda
print((lambda b: (a := np.ones((b,b))).__setitem__((slice(1,-1), slice(1,-1)), 0) or a)(int(input("Размерность: "))),'\n')  # lambda + input
print((lambda b: (a := np.ones((b,b)), np.putmask(a, (np.arange(b)[:,None] % (b-1) != 0) & (np.arange(b) % (b-1) != 0), 0))[0])(int(input("Размерность: ")))) # lambda + mask

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]] 

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]] 

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]] 

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]] 



Размерность:  3


[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]] 



Размерность:  4


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [138]:
# Для массива формы (6, 7, 8) найдите индекс (x, y, z) 100-го элемента (нумерация с 0).
# используйте np.unravel_index(99, (6, 7, 8))
print("Индекс 100-го элемента:", idx:=np.unravel_index(99, (6, 7, 8)))                                            # Стандартный вывод
print("Индекс 100-го элемента:", tuple(int(i) for i in idx))                      # Преобразование в tuple с int
print("Индекс 100-го элемента:", tuple(map(int, idx)))                            # Использование map
i, j, k = map(int, idx)                                                          
print("Индекс 100-го элемента:", (i, j, k))                                       # Распаковка с преобразованием
print("Индекс 100-го элемента: (%d, %d, %d)" % idx)                               # Форматирование строки
print(f"Индекс 100-го элемента: ({int(idx[0])}, {int(idx[1])}, {int(idx[2])})")   # f-strings с явным преобразованием

Индекс 100-го элемента: (np.int64(1), np.int64(5), np.int64(3))
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)


In [149]:
# Перемножьте матрицу A (5x3) на матрицу B (3x2), выведите форму результата и сам результат.
# Подсказка: используйте оператор @ или np.dot(A, B)
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
result = A @ B
print(f"Исходные данные: {"\nA:\n"}{A}{"\nB:\n"}{B}")
print(f"\nФорма результата: {result.shape}")
print(f"\nРезультат:\n{result.round(3)}")
print(f"\nРезультат:\n{np.dot(A, B).round(4)}")

Исходные данные: 
A:
[[0.62832005 0.3273519  0.45636234]
 [0.29020308 0.31601009 0.6696084 ]
 [0.86946374 0.5577833  0.84243245]
 [0.26368291 0.54319559 0.19115566]
 [0.49830973 0.06542774 0.92192796]]
B:
[[0.63588643 0.73771756]
 [0.39223163 0.87504837]
 [0.53995177 0.24901741]]

Форма результата: (5, 2)

Результат:
[[0.774 0.864]
 [0.67  0.657]
 [1.227 1.339]
 [0.484 0.717]
 [0.84  0.654]]

Результат:
[[0.7744 0.8636]
 [0.67   0.6574]
 [1.2265 1.3393]
 [0.4839 0.7174]
 [0.8403 0.6544]]
