# NumPy: шпаргалка для начинающих https://habr.com/ru/articles/768188/

### Создание массивов и базовые свойства

In [1]:
import numpy as np
import scipy.linalg
from scipy import special


# Создание из списка + явный тип
x = np.array([1, 2, 3], dtype=np.int32)
print("x =", x, "| dtype:", x.dtype)

x = [1 2 3] | dtype: int32


In [2]:
# Последовательности чисел
A = np.arange(21)                   # 0,1,2,..,19,20
print("A =", A)

B = np.linspace(0.0, 1.0, 21)      # 21 точка от 0 до 1 включительно
print("B =", B)

A = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
B = [0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]


In [3]:
# Матрицы-заготовки
Z = np.zeros((2, 3))               # все нули
O = np.ones((2, 3))                # все единицы
F = np.full((2, 3), 7)             # все семерки
I = np.eye(3)                      # единичная матрица 3х3
print("Z:\n", Z)
print("O:\n", O)
print("F:\n", F)
print("I:\n", I)

Z:
 [[0. 0. 0.]
 [0. 0. 0.]]
O:
 [[1. 1. 1.]
 [1. 1. 1.]]
F:
 [[7 7 7]
 [7 7 7]]
I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Базовые свойства формы и размера
M = np.arange(1, 13).reshape(3, 4)   # меняем форму без копии данных
print("M:\n", M)
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size, "| dtype:", M.dtype)
M = np.array(M, dtype=np.int32)
M = M.reshape(4, 3)
print("M:\n", M)
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size, "| dtype:", M.dtype)

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4) | ndim: 2 | size: 12 | dtype: int64
M:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3) | ndim: 2 | size: 12 | dtype: int32


In [5]:
# Преобразование типа (создаёт копию)
M32 = M.astype(np.float32)
print("M32 dtype:", M32.dtype)
print(M.reshape(2, -1))

M32 dtype: float32
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
# Автоматический размер в reshape  через -1 (подбирается NumPy)
R = np.arange(8).reshape(2, -1)  # -1 => автоматически перераспределяется в 4 столбца
print("R:\n", R, "shape:", R.shape)

R:
 [[0 1 2 3]
 [4 5 6 7]] shape: (2, 4)




### Индексация и срезы массивов

In [7]:
A = np.arange(1, 13).reshape(3, 4)   # меняем форму без копии данных
print("A:\n", A)

# Доступ к элементу по индексу (строка, столбец)
print("A[1, 2] =", A[1, 2])          #элемент во 2-ой строке и 3-ем столбце

# Срезы (slice) по строкам и столбцам
print("A[0, :] =", A[0, :])          # вся первая строка
print("A[:, 1] =", A[:, 1])          # весь второй столбец

# Подмассив срезом
S = A[0:2, 1:3]
print("S:\n", S)

# Изменение через срез отражается в исходном массиве
S[0, 0] = -1
print("После изменений S:\n", A)

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A[1, 2] = 7
A[0, :] = [1 2 3 4]
A[:, 1] = [ 2  6 10]
S:
 [[2 3]
 [6 7]]
После изменений S:
 [[ 1 -1  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]




### Булева индексация (фильтрация данных)

In [8]:
A = np.arange(12).reshape(3, 4)
print("A:\n", A, "\n")

# Булева маска: True для чётных элементов
mask = (A % 2 == 0)
print("Маска:\n", mask, "\n")

# Применение маски
print("Чётные элементы:\n", A[mask], "\n")
print("Нечётные элементы:\n", A[~mask] , "\n")
print("Все элементы:\n", A[np.logical_or(mask, np.logical_not(mask))] , "\n")

# Булева маска для диапазона значений
mask2 = (A > 3) & (A < 10)
print("Маска (A > 3) & (A < 10):\n", mask2)
F = A[mask2]
print("Элементы от 4 до 9:", F, "\n")
print("Маска np.logical_and((A > 3), (A < 10)):\n", np.logical_and((A > 3), (A < 10)))
print("Элементы от 4 до 9:", A[np.logical_and((A > 3), (A < 10))], "\n")

A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Маска:
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]] 

Чётные элементы:
 [ 0  2  4  6  8 10] 

Нечётные элементы:
 [ 1  3  5  7  9 11] 

Все элементы:
 [ 0  1  2  3  4  5  6  7  8  9 10 11] 

Маска (A > 3) & (A < 10):
 [[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
Элементы от 4 до 9: [4 5 6 7 8 9] 

Маска np.logical_and((A > 3), (A < 10)):
 [[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
Элементы от 4 до 9: [4 5 6 7 8 9] 





### Продвинутая индексация (fance indexing) пересечение строк со столбцами - \#

In [9]:
A = np.arange(12).reshape(3, 4)
print("A = np.arange(12).reshape(3, 4)\n A:\n", A, "\nA.shape:", A.shape, "\n")

# Выбор целых строк
rows = [0, 2]
print("rows:", rows, "\n")

R = A[rows]
print("Строки 0 и 2\n R = A[rows] \n R:\n", R,"\nR.shape:", R.shape, "\n")

# Выбор элементов по координатам
rows = np.array([0, 2])
print("rows = np.array([0, 2]) \n rows rows.shape:\n", rows,rows.shape, "\n")
cols = np.array([1, 3])
print("cols = np.array([1, 3]) \n cols cols.shape:\n", cols,cols.shape, "\n")

print("Транспонирование строки 0 и 2:\n rows[:,None] rows[:,None].shape:\n", rows[:,None], rows[:,None].shape)

print("\nТождество np.array([[0], [2]])==rows[:,None] :\n", np.array([[0], [2]])==rows[:,None])

print(np.array([[0], [2]]).shape,rows[:,None].shape,"\n")

F = A[np.array([0, 2])[:,None], cols]
print("\nЭлементы по координатам:\n F = A[np.array([0, 2])[:,None], cols] | F:\n", F)

print("rows:", rows, "cols:", cols)
print("rows.shape:", rows.shape,"cols.shape:", cols.shape)

F1 = A[rows, cols]
print("Элементы по координатам 2:\n", F1)

#Перестановка столбцов
print("\nСтолбцы в новом порядке:\n", A[:,[2,0,3,1]])

A = np.arange(12).reshape(3, 4)
 A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
A.shape: (3, 4) 

rows: [0, 2] 

Строки 0 и 2
 R = A[rows] 
 R:
 [[ 0  1  2  3]
 [ 8  9 10 11]] 
R.shape: (2, 4) 

rows = np.array([0, 2]) 
 rows rows.shape:
 [0 2] (2,) 

cols = np.array([1, 3]) 
 cols cols.shape:
 [1 3] (2,) 

Транспонирование строки 0 и 2:
 rows[:,None] rows[:,None].shape:
 [[0]
 [2]] (2, 1)

Тождество np.array([[0], [2]])==rows[:,None] :
 [[ True]
 [ True]]
(2, 1) (2, 1) 


Элементы по координатам:
 F = A[np.array([0, 2])[:,None], cols] | F:
 [[ 1  3]
 [ 9 11]]
rows: [0 2] cols: [1 3]
rows.shape: (2,) cols.shape: (2,)
Элементы по координатам 2:
 [ 1 11]

Столбцы в новом порядке:
 [[ 2  0  3  1]
 [ 6  4  7  5]
 [10  8 11  9]]


In [10]:
x = np.array([1, 4, 9, 16])
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Унарные функции:")
print("np.sqrt(x):", np.sqrt(x))        # квадратный корень
print("np.exp(x):", np.exp(x))          # экспонента
print("np.log(x):", np.log(x))          # натуральный логарифм
print("np.log10(x):", np.log10(x))      # десятичный логарифм
print("np.sin(x):", np.sin(x))          # синус
print("np.cos(x):", np.cos(x))          # косинус
print("np.tan(x):", np.tan(x))          # тангенс
print("np.arcsin(x/100):", np.arcsin(x/100))  # арксинус
print("np.arccos(x/100):", np.arccos(x/100))  # арккосинус
print("np.arctan(x):", np.arctan(x))    # арктангенс
print("np.abs(x):", np.abs(x))          # модуль
print("np.negative(x):", np.negative(x))# смена знака
print("np.reciprocal(x):", np.reciprocal(x))  # обратное значение
print("np.square(x):", np.square(x))    # квадрат
print("np.sign(x):", np.sign(x))        # знак числа
print("np.ceil(x):", np.ceil(x))        # округление вверх
print("np.floor(x):", np.floor(x))      # округление вниз
print("np.round(x):", np.round(x))      # округление
print("np.isfinite(x):", np.isfinite(x))# проверка на конечность
print("np.isnan(x):", np.isnan(x))      # проверка на NaN
print("np.isinf(x):", np.isinf(x))      # проверка на бесконечность

# Бинарные ufunc (два массива на входе)
print("\nБинарные функции:")
print("a + b:", np.add(a, b))           # сложение
print("a - b:", np.subtract(a, b))      # вычитание
print("a * b:", np.multiply(a, b))      # умножение
print("a / b:", np.divide(a, b))        # деление
print("a // b:", np.floor_divide(a, b)) # целочисленное деление
print("a % b:", np.mod(a, b))           # остаток от деления
print("a ** b:", np.power(a, b))        # возведение в степень
print("a > b:", np.greater(a, b))       # больше
print("a < b:", np.less(a, b))          # меньше
print("a >= b:", np.greater_equal(a, b))# больше или равно
print("a <= b:", np.less_equal(a, b))   # меньше или равно
print("a == b:", np.equal(a, b))        # равно
print("a != b:", np.not_equal(a, b))    # не равно
print("max(a,b):", np.maximum(a, b))    # поэлементный максимум
print("min(a,b):", np.minimum(a, b))    # поэлементный минимум
print("a & b:", np.bitwise_and(a, b))   # побитовое И
print("a | b:", np.bitwise_or(a, b))    # побитовое ИЛИ
print("a ^ b:", np.bitwise_xor(a, b))   # побитовое XOR
print("arctan2(a,b):", np.arctan2(a, b))# арктангенс от a/b
print("hypot(a,b):", np.hypot(a, b))    # гипотенуза sqrt(a² + b²)
print("copysign(a,b):", np.copysign(a, b))  # копирование знака

# Полезные агрегирующие (CТАТИСТИЧЕСКИЕ) ufunc:
print("\nАгрегирующие (CТАТИСТИЧЕСКИЕ) функции:")
print("np.sum(a):", np.sum(a))          # сумма всех элементов
print("np.prod(a):", np.prod(a))        # произведение всех элементов
print("np.mean(a):", np.mean(a))        # среднее значение
print("np.std(a):", np.std(a))          # стандартное отклонение
print("np.var(a):", np.var(a))          # дисперсия
print("np.min(a):", np.min(a))          # минимальное значение
print("np.max(a):", np.max(a))          # максимальное значение
print("np.argmin(a):", np.argmin(a))    # индекс минимального элемента
print("np.argmax(a):", np.argmax(a))    # индекс максимального элемента

# Статистика по осям
A = np.arange(1,10).reshape(3, 3)
print("\nA:\n", A)
print("Сумма по строкам np.sum(A, axis=1):", np.sum(A, axis=1))          # сумма всех элементов
print("Сумма по столбцам np.sum(A, axis=0):", np.sum(A, axis=0))          # сумма всех элементов
print("Седнее по столбцам np.mean(A, axis=0):", np.mean(A, axis=0))        # среднее значение

# Дополнительные унарные ufunc:
print("\nДополнительные унарные функции:")
print("np.radians(x):", np.radians(x))      # градусы в радианы
print("np.degrees(x):", np.degrees(x))      # радианы в градусы
print("np.sinh(x):", np.sinh(x))            # гиперболический синус
print("np.cosh(x):", np.cosh(x))            # гиперболический косинус
print("np.tanh(x):", np.tanh(x))            # гиперболический тангенс
print("np.arcsinh(x):", np.arcsinh(x))      # обратный гиперболический синус
print("np.arccosh(x + 1):", np.arccosh(x + 1)) # обратный гиперб. косинус
print("np.arctanh(x/100):", np.arctanh(x/100)) # обратный гиперб. тангенс
print("np.cbrt(x):", np.cbrt(x))            # кубический корень
print("np.log1p(x):", np.log1p(x))          # log(1 + x) - точный для малых x
print("np.expm1(x):", np.expm1(x))          # exp(x) - 1 - точный для малых x
print("np.positive(x):", np.positive(x))    # унарный плюс (копирование)
print("np.conj(x):", np.conj(x))            # комплексное сопряжение
print("np.real(x):", np.real(x))            # действительная часть
print("np.imag(x):", np.imag(x))            # мнимая часть
print("np.angle(x):", np.angle(x))          # фаза комплексного числа

# Дополнительные бинарные ufunc:
print("\nДополнительные бинарные функции:")
print("np.fmax(a,b):", np.fmax(a, b))       # максимум (игнорирует NaN)
print("np.fmin(a,b):", np.fmin(a, b))       # минимум (игнорирует NaN)
print("np.fmod(a,b):", np.fmod(a, b))       # остаток от деления (как fmod в C)
print("np.ldexp(a, b):", np.ldexp(a, b))    # a * 2^b
print("np.logaddexp(a,b):", np.logaddexp(a, b)) # log(exp(a) + exp(b))
print("np.logaddexp2(a,b):", np.logaddexp2(a, b)) # log2(exp2(a) + exp2(b))
print("np.nextafter(a,b):", np.nextafter(a, b)) # следующее число после a в направлении b
print("np.remainder(a,b):", np.remainder(a, b)) # остаток (как %)
print("np.true_divide(a,b):", np.true_divide(a, b)) # истинное деление
print("np.left_shift(a,1):", np.left_shift(a, 1)) # побитовый сдвиг влево
print("np.right_shift(a,1):", np.right_shift(a, 1)) # побитовый сдвиг вправо

# Специальные математические ufunc:
print("\nСпециальные математические функции (из scipy.special):")
print("special.gamma(x):", special.gamma(x))          # гамма-функция
print("special.loggamma(x):", special.loggamma(x))    # логарифм гамма-функции
print("special.erf(x):", special.erf(x))              # функция ошибок
print("special.erfc(x):", special.erfc(x))            # дополнение функции ошибок
print("special.erfinv(x/10):", special.erfinv(x/10))  # обратная функция ошибок
print("special.i0(x):", special.i0(x))                # модиф. функция Бесселя 0-го рода
print("special.sinc(x):", special.sinc(x))            # sinc функция

# Логические ufunc:
print("\nЛогические функции:")
print("np.logical_and(a>2, b<30):", np.logical_and(a>2, b<30))
print("np.logical_or(a>2, b<30):", np.logical_or(a>2, b<30))
print("np.logical_xor(a>2, b<30):", np.logical_xor(a>2, b<30))
print("np.logical_not(a>2):", np.logical_not(a>2))

#Проверки:
print("\nФункции проверки:")
print("np.isreal(x):", np.isreal(x))        # проверка на действительное число
print("np.iscomplex(x):", np.iscomplex(x))  # проверка на комплексное число
print("np.isfinite(x):", np.isfinite(x))    # проверка на конечность
print("np.isposinf(x):", np.isposinf(x))    # проверка на +бесконечность
print("np.isneginf(x):", np.isneginf(x))    # проверка на -бесконечность

Унарные функции:
np.sqrt(x): [1. 2. 3. 4.]
np.exp(x): [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
np.log(x): [0.         1.38629436 2.19722458 2.77258872]
np.log10(x): [0.         0.60205999 0.95424251 1.20411998]
np.sin(x): [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
np.cos(x): [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
np.tan(x): [ 1.55740772  1.15782128 -0.45231566  0.30063224]
np.arcsin(x/100): [0.01000017 0.04001067 0.09012195 0.16069065]
np.arccos(x/100): [1.56079616 1.53078565 1.48067438 1.41010567]
np.arctan(x): [0.78539816 1.32581766 1.46013911 1.50837752]
np.abs(x): [ 1  4  9 16]
np.negative(x): [ -1  -4  -9 -16]
np.reciprocal(x): [1 0 0 0]
np.square(x): [  1  16  81 256]
np.sign(x): [1 1 1 1]
np.ceil(x): [ 1  4  9 16]
np.floor(x): [ 1  4  9 16]
np.round(x): [ 1  4  9 16]
np.isfinite(x): [ True  True  True  True]
np.isnan(x): [False False False False]
np.isinf(x): [False False False False]

Бинарные функции:
a + b: [11 22 33 44]
a - b: [ -9 -18 

In [11]:


### Линейная алгебра в NumPy

In [13]:


# Создадим матрицы для примеров
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([1, 2])

print("Определитель матрицы A:", np.linalg.det(A))
print("Обратная матрица A:\n", np.linalg.inv(A))
print("Умножение матриц A×B (оператор @):\n", A @ B)
print("Умножение матриц A×B (функция matmul):\n", np.matmul(A, B))
print("След матрицы A (сумма диагональных элементов):", np.trace(A))

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Собственные значения A:", eigenvalues)
print("Собственные векторы A:\n", eigenvectors)
print("Ранг матрицы A:", np.linalg.matrix_rank(A))
print("Норма Фробениуса матрицы A:", np.linalg.norm(A))
print("L2 норма вектора v:", np.linalg.norm(v))
print("L1 норма вектора v:", np.linalg.norm(v, ord=1))

b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Решение СЛАУ Ax = b:", x)
print("Псевдообратная матрица A (Мур-Пенроуза):\n", np.linalg.pinv(A))

Q, R = np.linalg.qr(A)
print("Q матрица из QR-разложения:\n", Q)
print("R матрица из QR-разложения:\n", R)

U, S, Vt = np.linalg.svd(A)
print("U матрица из SVD-разложения:\n", U)
print("Сингулярные значения из SVD-разложения:", S)
print("V транспонированная из SVD-разложения:\n", Vt)

# LU-разложение доступно в scipy (отсутствует в numpy.linalg)
P, L, U_lu = scipy.linalg.lu(A)
print("P матрица перестановок из LU-разложения:\n", P)
print("L матрица из LU-разложения:\n", L)
print("U матрица из LU-разложения:\n", U_lu)

# Только для симметричных положительно определенных матриц
C = np.array([[4, 2], [2, 5]])
L_chol = np.linalg.cholesky(C)
print("Cholesky разложение для симметричной матрицы:\n", L_chol)

# Матричная экспонента также доступна в scipy.linalg
print("Матричная экспонента e^A:\n", scipy.linalg.expm(A))
print("Логарифм определителя A:", np.linalg.slogdet(A))
print("Условное число матрицы A:", np.linalg.cond(A))
print("Тензорное произведение Кронекера A и B:\n", np.kron(A, B))

a_3d = np.array([1, 0, 0])
b_3d = np.array([0, 1, 0])
print("Векторное произведение 3D векторов:", np.cross(a_3d, b_3d))
print("Скалярное произведение векторов (функция dot):", np.dot(v, v))
print("Скалярное произведение векторов (оператор @):", v @ v)

# Полный пример использования
print("\n" + "="*50)
print("ПОЛНЫЙ ПРИМЕР ИСПОЛЬЗОВАНИЯ:")
A_example = np.array([[4, 2], [1, 3]])
b_example = np.array([1, 2])
print("Матрица A:\n", A_example)
print("Вектор b:", b_example)
print("Определитель A:", np.linalg.det(A_example))
print("Обратная матрица A:\n", np.linalg.inv(A_example))
print("Решение Ax = b:", np.linalg.solve(A_example, b_example))
print("Собственные значения A:", np.linalg.eig(A_example)[0])

Определитель матрицы A: -2.0000000000000004
Обратная матрица A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Умножение матриц A×B (оператор @):
 [[19 22]
 [43 50]]
Умножение матриц A×B (функция matmul):
 [[19 22]
 [43 50]]
След матрицы A (сумма диагональных элементов): 5
Собственные значения A: [-0.37228132  5.37228132]
Собственные векторы A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Ранг матрицы A: 2
Норма Фробениуса матрицы A: 5.477225575051661
L2 норма вектора v: 2.23606797749979
L1 норма вектора v: 3.0
Решение СЛАУ Ax = b: [0.  0.5]
Псевдообратная матрица A (Мур-Пенроуза):
 [[-2.   1. ]
 [ 1.5 -0.5]]
Q матрица из QR-разложения:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R матрица из QR-разложения:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
U матрица из SVD-разложения:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Сингулярные значения из SVD-разложения: [5.4649857  0.36596619]
V транспонированная из SVD-разложения:
 [[-0.57604844 -0.81741556]
 [ 0.81

In [ ]:


### Генерация случайных чисел в NUmPy