### Создание массивов и базовые свойства

In [1]:
import numpy as np

# Создание из списка + явный тип
x = np.array([1, 2, 3], dtype=np.int32)
print("x =", x, "| dtype:", x.dtype)

x = [1 2 3] | dtype: int32


In [2]:
# Последовательности чисел
A = np.arange(21)                   # 0,1,2,..,19,20
print("A =", A)

B = np.linspace(0.0, 1.0, 21)      # 21 точка от 0 до 1 включительно
print("B =", B)

A = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
B = [0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]


In [3]:
# Матрицы-заготовки
Z = np.zeros((2, 3))               # все нули
O = np.ones((2, 3))                # все единицы
F = np.full((2, 3), 7)             # все семерки
I = np.eye(3)                      # единичная матрица 3х3
print("Z:\n", Z)
print("O:\n", O)
print("F:\n", F)
print("I:\n", I)

Z:
 [[0. 0. 0.]
 [0. 0. 0.]]
O:
 [[1. 1. 1.]
 [1. 1. 1.]]
F:
 [[7 7 7]
 [7 7 7]]
I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Базовые свойства формы и размера
M = np.arange(1, 13).reshape(3, 4)   # меняем форму без копии данных
print("M:\n", M)
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size, "| dtype:", M.dtype)
M = np.array(M, dtype=np.int32)
M = M.reshape(4, 3)
print("M:\n", M)
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size, "| dtype:", M.dtype)

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4) | ndim: 2 | size: 12 | dtype: int64
M:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3) | ndim: 2 | size: 12 | dtype: int32


In [8]:
# Преобразование типа (создаёт копию)
M32 = M.astype(np.float32)
print("M32 dtype:", M32.dtype)
print(M.reshape(2, -1))

M32 dtype: float32
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [10]:
# Автоматический размер в reshape  через -1 (подбирается NumPy)
R = np.arange(8).reshape(2, -1)  # -1 => автоматически перераспределяется в 4 столбца
print("R:\n", R, "shape:", R.shape)

R:
 [[0 1 2 3]
 [4 5 6 7]] shape: (2, 4)




### Индексация и срезы массивов

In [17]:
A = np.arange(1, 13).reshape(3, 4)   # меняем форму без копии данных
print("A:\n", A)

# Доступ к элементу по индексу (строка, столбец)
print("A[1, 2] =", A[1, 2])          #элемент во 2-ой строке и 3-ем столбце

# Срезы (slice) по строкам и столбцам
print("A[0, :] =", A[0, :])          # вся первая строка
print("A[:, 1] =", A[:, 1])          # весь второй столбец

# Подмассив срезом
S = A[0:2, 1:3]
print("S:\n", S)

# Изменение через срез отражается в исходном массиве
S[0, 0] = -1
print("После изменений S:\n", A)

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A[1, 2] = 7
A[0, :] = [1 2 3 4]
A[:, 1] = [ 2  6 10]
S:
 [[2 3]
 [6 7]]
После изменений S:
 [[ 1 -1  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]




### Булева индексация (фильтрация данных)

In [21]:
A = np.arange(12).reshape(3, 4)
print("A:\n", A, "\n")

# Булева маска: True для чётных элементов
mask = (A % 2 == 0)
print("Маска:\n", mask, "\n")

# Применение маски
E = A[mask]
print("Чётные элементы:\n", E, "\n")

# Булева маска для диапазона значений
mask2 = (A > 3) & (A < 10)
print("Маска (A > 3) & (A < 10):\n", mask2, "\n")

F = A[mask2]
print("Элементы от 4 до 9:", F)

A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Маска:
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]] 

Чётные элементы:
 [ 0  2  4  6  8 10] 

Маска (A > 3) & (A < 10):
 [[False False False False]
 [ True  True  True  True]
 [ True  True False False]] 

Элементы от 4 до 9: [4 5 6 7 8 9]




### Продвинутая индексация (fance indexing)

In [22]:
A = np.arange(12).reshape(3, 4)
print("A:\n", A, "\n")

# Выбор целых строк
rows = [0, 2]
R = A[rows]
print("Строки 0 и 2:\n", R, "\n")

A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Строки 0 и 2:
 [[ 0  1  2  3]
 [ 8  9 10 11]] 

