# NumPy: шпаргалка для начинающих https://habr.com/ru/articles/768188/

### Создание массивов и базовые свойства

In [1]:
import numpy as np
import scipy.linalg
from scipy import special


# Создание из списка + явный тип
x = np.array([1, 2, 3], dtype=np.int32)
print("x =", x, "| dtype:", x.dtype)

x = [1 2 3] | dtype: int32


In [2]:
# Последовательности чисел
A = np.arange(21)                   # 0,1,2,..,19,20
print("A =", A)

B = np.linspace(0.0, 1.0, 21)      # 21 точка от 0 до 1 включительно
print("B =", B)

A = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
B = [0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]


In [3]:
# Матрицы-заготовки
Z = np.zeros((2, 3))               # все нули
O = np.ones((2, 3))                # все единицы
F = np.full((2, 3), 7)             # все семерки
I = np.eye(3)                      # единичная матрица 3х3
print("Z:\n", Z)
print("O:\n", O)
print("F:\n", F)
print("I:\n", I)

Z:
 [[0. 0. 0.]
 [0. 0. 0.]]
O:
 [[1. 1. 1.]
 [1. 1. 1.]]
F:
 [[7 7 7]
 [7 7 7]]
I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Базовые свойства формы и размера
M = np.arange(1, 13).reshape(3, 4)   # меняем форму без копии данных
print("M:\n", M)
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size, "| dtype:", M.dtype)
M = np.array(M, dtype=np.int32)
M = M.reshape(4, 3)
print("M:\n", M)
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size, "| dtype:", M.dtype)

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
shape: (3, 4) | ndim: 2 | size: 12 | dtype: int64
M:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3) | ndim: 2 | size: 12 | dtype: int32


In [5]:
# Преобразование типа (создаёт копию)
M32 = M.astype(np.float32)
print("M32 dtype:", M32.dtype)
print(M.reshape(2, -1))

M32 dtype: float32
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
# Автоматический размер в reshape  через -1 (подбирается NumPy)
R = np.arange(8).reshape(2, -1)  # -1 => автоматически перераспределяется в 4 столбца
print("R:\n", R, "shape:", R.shape)

R:
 [[0 1 2 3]
 [4 5 6 7]] shape: (2, 4)




### Индексация и срезы массивов

In [7]:
A = np.arange(1, 13).reshape(3, 4)   # меняем форму без копии данных
print("A:\n", A)

# Доступ к элементу по индексу (строка, столбец)
print("A[1, 2] =", A[1, 2])          #элемент во 2-ой строке и 3-ем столбце

# Срезы (slice) по строкам и столбцам
print("A[0, :] =", A[0, :])          # вся первая строка
print("A[:, 1] =", A[:, 1])          # весь второй столбец

# Подмассив срезом
S = A[0:2, 1:3]
print("S:\n", S)

# Изменение через срез отражается в исходном массиве
S[0, 0] = -1
print("После изменений S:\n", A)

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
A[1, 2] = 7
A[0, :] = [1 2 3 4]
A[:, 1] = [ 2  6 10]
S:
 [[2 3]
 [6 7]]
После изменений S:
 [[ 1 -1  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]




### Булева индексация (фильтрация данных)

In [8]:
A = np.arange(12).reshape(3, 4)
print("A:\n", A, "\n")

# Булева маска: True для чётных элементов
mask = (A % 2 == 0)
print("Маска:\n", mask, "\n")

# Применение маски
print("Чётные элементы:\n", A[mask], "\n")
print("Нечётные элементы:\n", A[~mask] , "\n")
print("Все элементы:\n", A[np.logical_or(mask, np.logical_not(mask))] , "\n")

# Булева маска для диапазона значений
mask2 = (A > 3) & (A < 10)
print("Маска (A > 3) & (A < 10):\n", mask2)
F = A[mask2]
print("Элементы от 4 до 9:", F, "\n")
print("Маска np.logical_and((A > 3), (A < 10)):\n", np.logical_and((A > 3), (A < 10)))
print("Элементы от 4 до 9:", A[np.logical_and((A > 3), (A < 10))], "\n")

A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Маска:
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]] 

Чётные элементы:
 [ 0  2  4  6  8 10] 

Нечётные элементы:
 [ 1  3  5  7  9 11] 

Все элементы:
 [ 0  1  2  3  4  5  6  7  8  9 10 11] 

Маска (A > 3) & (A < 10):
 [[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
Элементы от 4 до 9: [4 5 6 7 8 9] 

Маска np.logical_and((A > 3), (A < 10)):
 [[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
Элементы от 4 до 9: [4 5 6 7 8 9] 





### Продвинутая индексация (fance indexing) пересечение строк со столбцами - \#

In [9]:
A = np.arange(12).reshape(3, 4)
print("A = np.arange(12).reshape(3, 4)\n A:\n", A, "\nA.shape:", A.shape, "\n")

# Выбор целых строк
rows = [0, 2]
print("rows:", rows, "\n")

R = A[rows]
print("Строки 0 и 2\n R = A[rows] \n R:\n", R,"\nR.shape:", R.shape, "\n")

# Выбор элементов по координатам
rows = np.array([0, 2])
print("rows = np.array([0, 2]) \n rows rows.shape:\n", rows,rows.shape, "\n")
cols = np.array([1, 3])
print("cols = np.array([1, 3]) \n cols cols.shape:\n", cols,cols.shape, "\n")

print("Транспонирование строки 0 и 2:\n rows[:,None] rows[:,None].shape:\n", rows[:,None], rows[:,None].shape)

print("\nТождество np.array([[0], [2]])==rows[:,None] :\n", np.array([[0], [2]])==rows[:,None])

print(np.array([[0], [2]]).shape,rows[:,None].shape,"\n")

F = A[np.array([0, 2])[:,None], cols]
print("\nЭлементы по координатам:\n F = A[np.array([0, 2])[:,None], cols] | F:\n", F)

print("rows:", rows, "cols:", cols)
print("rows.shape:", rows.shape,"cols.shape:", cols.shape)

F1 = A[rows, cols]
print("Элементы по координатам 2:\n", F1)

#Перестановка столбцов
print("\nСтолбцы в новом порядке:\n", A[:,[2,0,3,1]])

A = np.arange(12).reshape(3, 4)
 A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
A.shape: (3, 4) 

rows: [0, 2] 

Строки 0 и 2
 R = A[rows] 
 R:
 [[ 0  1  2  3]
 [ 8  9 10 11]] 
R.shape: (2, 4) 

rows = np.array([0, 2]) 
 rows rows.shape:
 [0 2] (2,) 

cols = np.array([1, 3]) 
 cols cols.shape:
 [1 3] (2,) 

Транспонирование строки 0 и 2:
 rows[:,None] rows[:,None].shape:
 [[0]
 [2]] (2, 1)

Тождество np.array([[0], [2]])==rows[:,None] :
 [[ True]
 [ True]]
(2, 1) (2, 1) 


Элементы по координатам:
 F = A[np.array([0, 2])[:,None], cols] | F:
 [[ 1  3]
 [ 9 11]]
rows: [0 2] cols: [1 3]
rows.shape: (2,) cols.shape: (2,)
Элементы по координатам 2:
 [ 1 11]

Столбцы в новом порядке:
 [[ 2  0  3  1]
 [ 6  4  7  5]
 [10  8 11  9]]


In [10]:
x = np.array([1, 4, 9, 16])
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Унарные функции:")
print("np.sqrt(x):", np.sqrt(x))        # квадратный корень
print("np.exp(x):", np.exp(x))          # экспонента
print("np.log(x):", np.log(x))          # натуральный логарифм
print("np.log10(x):", np.log10(x))      # десятичный логарифм
print("np.sin(x):", np.sin(x))          # синус
print("np.cos(x):", np.cos(x))          # косинус
print("np.tan(x):", np.tan(x))          # тангенс
print("np.arcsin(x/100):", np.arcsin(x/100))  # арксинус
print("np.arccos(x/100):", np.arccos(x/100))  # арккосинус
print("np.arctan(x):", np.arctan(x))    # арктангенс
print("np.abs(x):", np.abs(x))          # модуль
print("np.negative(x):", np.negative(x))# смена знака
print("np.reciprocal(x):", np.reciprocal(x))  # обратное значение
print("np.square(x):", np.square(x))    # квадрат
print("np.sign(x):", np.sign(x))        # знак числа
print("np.ceil(x):", np.ceil(x))        # округление вверх
print("np.floor(x):", np.floor(x))      # округление вниз
print("np.round(x):", np.round(x))      # округление
print("np.isfinite(x):", np.isfinite(x))# проверка на конечность
print("np.isnan(x):", np.isnan(x))      # проверка на NaN
print("np.isinf(x):", np.isinf(x))      # проверка на бесконечность

# Бинарные ufunc (два массива на входе)
print("\nБинарные функции:")
print("a + b:", np.add(a, b))           # сложение
print("a - b:", np.subtract(a, b))      # вычитание
print("a * b:", np.multiply(a, b))      # умножение
print("a / b:", np.divide(a, b))        # деление
print("a // b:", np.floor_divide(a, b)) # целочисленное деление
print("a % b:", np.mod(a, b))           # остаток от деления
print("a ** b:", np.power(a, b))        # возведение в степень
print("a > b:", np.greater(a, b))       # больше
print("a < b:", np.less(a, b))          # меньше
print("a >= b:", np.greater_equal(a, b))# больше или равно
print("a <= b:", np.less_equal(a, b))   # меньше или равно
print("a == b:", np.equal(a, b))        # равно
print("a != b:", np.not_equal(a, b))    # не равно
print("max(a,b):", np.maximum(a, b))    # поэлементный максимум
print("min(a,b):", np.minimum(a, b))    # поэлементный минимум
print("a & b:", np.bitwise_and(a, b))   # побитовое И
print("a | b:", np.bitwise_or(a, b))    # побитовое ИЛИ
print("a ^ b:", np.bitwise_xor(a, b))   # побитовое XOR
print("arctan2(a,b):", np.arctan2(a, b))# арктангенс от a/b
print("hypot(a,b):", np.hypot(a, b))    # гипотенуза sqrt(a² + b²)
print("copysign(a,b):", np.copysign(a, b))  # копирование знака

# Полезные агрегирующие (CТАТИСТИЧЕСКИЕ) ufunc:
print("\nАгрегирующие (CТАТИСТИЧЕСКИЕ) функции:")
print("np.sum(a):", np.sum(a))          # сумма всех элементов
print("np.prod(a):", np.prod(a))        # произведение всех элементов
print("np.mean(a):", np.mean(a))        # среднее значение
print("np.std(a):", np.std(a))          # стандартное отклонение
print("np.var(a):", np.var(a))          # дисперсия
print("np.min(a):", np.min(a))          # минимальное значение
print("np.max(a):", np.max(a))          # максимальное значение
print("np.argmin(a):", np.argmin(a))    # индекс минимального элемента
print("np.argmax(a):", np.argmax(a))    # индекс максимального элемента

# Статистика по осям
A = np.arange(1,10).reshape(3, 3)
print("\nA:\n", A)
print("Сумма по строкам np.sum(A, axis=1):", np.sum(A, axis=1))          # сумма всех элементов
print("Сумма по столбцам np.sum(A, axis=0):", np.sum(A, axis=0))          # сумма всех элементов
print("Седнее по столбцам np.mean(A, axis=0):", np.mean(A, axis=0))        # среднее значение

# Дополнительные унарные ufunc:
print("\nДополнительные унарные функции:")
print("np.radians(x):", np.radians(x))      # градусы в радианы
print("np.degrees(x):", np.degrees(x))      # радианы в градусы
print("np.sinh(x):", np.sinh(x))            # гиперболический синус
print("np.cosh(x):", np.cosh(x))            # гиперболический косинус
print("np.tanh(x):", np.tanh(x))            # гиперболический тангенс
print("np.arcsinh(x):", np.arcsinh(x))      # обратный гиперболический синус
print("np.arccosh(x + 1):", np.arccosh(x + 1)) # обратный гиперб. косинус
print("np.arctanh(x/100):", np.arctanh(x/100)) # обратный гиперб. тангенс
print("np.cbrt(x):", np.cbrt(x))            # кубический корень
print("np.log1p(x):", np.log1p(x))          # log(1 + x) - точный для малых x
print("np.expm1(x):", np.expm1(x))          # exp(x) - 1 - точный для малых x
print("np.positive(x):", np.positive(x))    # унарный плюс (копирование)
print("np.conj(x):", np.conj(x))            # комплексное сопряжение
print("np.real(x):", np.real(x))            # действительная часть
print("np.imag(x):", np.imag(x))            # мнимая часть
print("np.angle(x):", np.angle(x))          # фаза комплексного числа

# Дополнительные бинарные ufunc:
print("\nДополнительные бинарные функции:")
print("np.fmax(a,b):", np.fmax(a, b))       # максимум (игнорирует NaN)
print("np.fmin(a,b):", np.fmin(a, b))       # минимум (игнорирует NaN)
print("np.fmod(a,b):", np.fmod(a, b))       # остаток от деления (как fmod в C)
print("np.ldexp(a, b):", np.ldexp(a, b))    # a * 2^b
print("np.logaddexp(a,b):", np.logaddexp(a, b)) # log(exp(a) + exp(b))
print("np.logaddexp2(a,b):", np.logaddexp2(a, b)) # log2(exp2(a) + exp2(b))
print("np.nextafter(a,b):", np.nextafter(a, b)) # следующее число после a в направлении b
print("np.remainder(a,b):", np.remainder(a, b)) # остаток (как %)
print("np.true_divide(a,b):", np.true_divide(a, b)) # истинное деление
print("np.left_shift(a,1):", np.left_shift(a, 1)) # побитовый сдвиг влево
print("np.right_shift(a,1):", np.right_shift(a, 1)) # побитовый сдвиг вправо

# Специальные математические ufunc:
print("\nСпециальные математические функции (из scipy.special):")
print("special.gamma(x):", special.gamma(x))          # гамма-функция
print("special.loggamma(x):", special.loggamma(x))    # логарифм гамма-функции
print("special.erf(x):", special.erf(x))              # функция ошибок
print("special.erfc(x):", special.erfc(x))            # дополнение функции ошибок
print("special.erfinv(x/10):", special.erfinv(x/10))  # обратная функция ошибок
print("special.i0(x):", special.i0(x))                # модиф. функция Бесселя 0-го рода
print("special.sinc(x):", special.sinc(x))            # sinc функция

# Логические ufunc:
print("\nЛогические функции:")
print("np.logical_and(a>2, b<30):", np.logical_and(a>2, b<30))
print("np.logical_or(a>2, b<30):", np.logical_or(a>2, b<30))
print("np.logical_xor(a>2, b<30):", np.logical_xor(a>2, b<30))
print("np.logical_not(a>2):", np.logical_not(a>2))

#Проверки:
print("\nФункции проверки:")
print("np.isreal(x):", np.isreal(x))        # проверка на действительное число
print("np.iscomplex(x):", np.iscomplex(x))  # проверка на комплексное число
print("np.isfinite(x):", np.isfinite(x))    # проверка на конечность
print("np.isposinf(x):", np.isposinf(x))    # проверка на +бесконечность
print("np.isneginf(x):", np.isneginf(x))    # проверка на -бесконечность

Унарные функции:
np.sqrt(x): [1. 2. 3. 4.]
np.exp(x): [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
np.log(x): [0.         1.38629436 2.19722458 2.77258872]
np.log10(x): [0.         0.60205999 0.95424251 1.20411998]
np.sin(x): [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
np.cos(x): [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
np.tan(x): [ 1.55740772  1.15782128 -0.45231566  0.30063224]
np.arcsin(x/100): [0.01000017 0.04001067 0.09012195 0.16069065]
np.arccos(x/100): [1.56079616 1.53078565 1.48067438 1.41010567]
np.arctan(x): [0.78539816 1.32581766 1.46013911 1.50837752]
np.abs(x): [ 1  4  9 16]
np.negative(x): [ -1  -4  -9 -16]
np.reciprocal(x): [1 0 0 0]
np.square(x): [  1  16  81 256]
np.sign(x): [1 1 1 1]
np.ceil(x): [ 1  4  9 16]
np.floor(x): [ 1  4  9 16]
np.round(x): [ 1  4  9 16]
np.isfinite(x): [ True  True  True  True]
np.isnan(x): [False False False False]
np.isinf(x): [False False False False]

Бинарные функции:
a + b: [11 22 33 44]
a - b: [ -9 -18 

In [11]:


### Линейная алгебра в NumPy

In [12]:


# Создадим матрицы для примеров
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([1, 2])

print("Определитель матрицы A:", np.linalg.det(A))
print("Обратная матрица A:\n", np.linalg.inv(A))
print("Умножение матриц A×B (оператор @):\n", A @ B)
print("Умножение матриц A×B (функция matmul):\n", np.matmul(A, B))
print("След матрицы A (сумма диагональных элементов):", np.trace(A))

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Собственные значения A:", eigenvalues)
print("Собственные векторы A:\n", eigenvectors)
print("Ранг матрицы A:", np.linalg.matrix_rank(A))
print("Норма Фробениуса матрицы A:", np.linalg.norm(A))
print("L2 норма вектора v:", np.linalg.norm(v))
print("L1 норма вектора v:", np.linalg.norm(v, ord=1))

b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Решение СЛАУ Ax = b:", x)
print("Псевдообратная матрица A (Мур-Пенроуза):\n", np.linalg.pinv(A))

Q, R = np.linalg.qr(A)
print("Q матрица из QR-разложения:\n", Q)
print("R матрица из QR-разложения:\n", R)

U, S, Vt = np.linalg.svd(A)
print("U матрица из SVD-разложения:\n", U)
print("Сингулярные значения из SVD-разложения:", S)
print("V транспонированная из SVD-разложения:\n", Vt)

# LU-разложение доступно в scipy (отсутствует в numpy.linalg)
P, L, U_lu = scipy.linalg.lu(A)
print("P матрица перестановок из LU-разложения:\n", P)
print("L матрица из LU-разложения:\n", L)
print("U матрица из LU-разложения:\n", U_lu)

# Только для симметричных положительно определенных матриц
C = np.array([[4, 2], [2, 5]])
L_chol = np.linalg.cholesky(C)
print("Cholesky разложение для симметричной матрицы:\n", L_chol)

# Матричная экспонента также доступна в scipy.linalg
print("Матричная экспонента e^A:\n", scipy.linalg.expm(A))
print("Логарифм определителя A:", np.linalg.slogdet(A))
print("Условное число матрицы A:", np.linalg.cond(A))
print("Тензорное произведение Кронекера A и B:\n", np.kron(A, B))

a_3d = np.array([1, 0, 0])
b_3d = np.array([0, 1, 0])
print("Векторное произведение 3D векторов:", np.cross(a_3d, b_3d))
print("Скалярное произведение векторов (функция dot):", np.dot(v, v))
print("Скалярное произведение векторов (оператор @):", v @ v)

# Полный пример использования
print("\n" + "="*50)
print("ПОЛНЫЙ ПРИМЕР ИСПОЛЬЗОВАНИЯ:")
A_example = np.array([[4, 2], [1, 3]])
b_example = np.array([1, 2])
print("Матрица A:\n", A_example)
print("Вектор b:", b_example)
print("Определитель A:", np.linalg.det(A_example))
print("Обратная матрица A:\n", np.linalg.inv(A_example))
print("Решение Ax = b:", np.linalg.solve(A_example, b_example))
print("Собственные значения A:", np.linalg.eig(A_example)[0])

Определитель матрицы A: -2.0000000000000004
Обратная матрица A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Умножение матриц A×B (оператор @):
 [[19 22]
 [43 50]]
Умножение матриц A×B (функция matmul):
 [[19 22]
 [43 50]]
След матрицы A (сумма диагональных элементов): 5
Собственные значения A: [-0.37228132  5.37228132]
Собственные векторы A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Ранг матрицы A: 2
Норма Фробениуса матрицы A: 5.477225575051661
L2 норма вектора v: 2.23606797749979
L1 норма вектора v: 3.0
Решение СЛАУ Ax = b: [0.  0.5]
Псевдообратная матрица A (Мур-Пенроуза):
 [[-2.   1. ]
 [ 1.5 -0.5]]
Q матрица из QR-разложения:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R матрица из QR-разложения:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
U матрица из SVD-разложения:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Сингулярные значения из SVD-разложения: [5.4649857  0.36596619]
V транспонированная из SVD-разложения:
 [[-0.57604844 -0.81741556]
 [ 0.81

In [13]:


### Генерация случайных чисел в NUmPy

In [18]:
import numpy as np

# Инициализация генератора случайных чисел
rng = np.random.default_rng()

print("\nГенерация случайного числа от 0 до 1:", np.random.random())
print("\nГенерация случайного числа от 0 до 1 (новый API):", rng.random())
print("\nМассив 3x3 случайных чисел от 0 до 1:\n", np.random.rand(3, 3))
print("\nМассив 2x4 случайных чисел от 0 до 1 (новый API):\n", rng.random((2, 4)))

print("\nСлучайное целое число от 0 до 10:", np.random.randint(0, 10))
print("\nМассив из 5 целых чисел от 1 до 100:\n", np.random.randint(1, 100, 5))
print("\nМатрица 2x3 целых чисел от 5 до 50:\n", np.random.randint(5, 50, (2, 3)))
print("\nЦелое число от 0 до 10 (новый API):", rng.integers(0, 10))
print("\nМассив из 6 целых чисел от 1 до 100 (новый API):\n", rng.integers(1, 100, 6))

print("\nВыбор из списка ['A', 'B', 'C', 'D']:", np.random.choice(['A', 'B', 'C', 'D']))
print("\nВыбор 3 элементов из списка с возвратом:", np.random.choice(['X', 'Y', 'Z'], size=3))
print("\nВыбор 3 элементов из списка без возврата:", np.random.choice(['X', 'Y', 'Z'], size=3, replace=False))
print("\nВыбор из списка с заданными вероятностями:", np.random.choice(['Win', 'Lose'], p=[0.3, 0.7], size=5))

print("\nСлучайное число из нормального распределения (μ=0, σ=1):", np.random.normal())
print("\n5 чисел из нормального распределения (μ=10, σ=2):", np.random.normal(10, 2, 5))
print("\nМатрица 2x2 из нормального распределения (новый API):\n", rng.normal(0, 1, (2, 2)))

print("\nСлучайное число из равномерного распределения [0,1):", np.random.uniform())
print("\n5 чисел из равномерного распределения [5, 15):", np.random.uniform(5, 15, 5))
print("\nМассив из равномерного распределения [0,1) (новый API):\n", rng.uniform(0, 1, 4))

print("\nСлучайное число из стандартного нормального распределения:", np.random.randn())
print("\nМассив 2x3 из стандартного нормального распределения:\n", np.random.randn(2, 3))
print("\nСлучайное число из стандартного нормального распределения (новый API):", rng.standard_normal())

data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("\nИсходный массив:", data)
np.random.shuffle(data)
print("\nПеремешанный массив:", data)

data2 = [1, 2, 3, 4, 5]
print("\nИсходный массив:", data2)
print("\nПеремешанная копия массива:", np.random.permutation(data2))
print("\nПеремешанная копия массива (новый API):", rng.permutation(data2))

print("\nСлучайное число из экспоненциального распределения (β=1):", np.random.exponential())
print("\n3 числа из экспоненциального распределения (β=2.5):", np.random.exponential(2.5, 3))
print("\nЭкспоненциальное распределение (новый API):", rng.exponential(1, 3))

print("\nСлучайное число из распределения Пуассона (λ=3):", np.random.poisson(3))
print("\nМассив из распределения Пуассона (λ=5):", np.random.poisson(5, 4))
print("\nРаспределение Пуассона (новый API):", rng.poisson(3, 5))

print("\nСлучайное число из биномиального распределения (n=10, p=0.5):", np.random.binomial(10, 0.5))
print("\n5 чисел из биномиального распределения (n=20, p=0.3):", np.random.binomial(20, 0.3, 5))
print("\nБиномиальное распределение (новый API):", rng.binomial(10, 0.5, 4))

print("\nУстановка seed для воспроизводимости:", np.random.seed(42))
print("\nДва случайных числа с seed:", np.random.random(), np.random.random())

print("\nУстановка seed для нового API:", np.random.default_rng(42))
print("\nДва случайных числа с seed (новый API):", rng.random(), rng.random())

print("\nВыборка из бета-распределения (α=2, β=5):", np.random.beta(2, 5))
print("\nВыборка из гамма-распределения (shape=2, scale=1):", np.random.gamma(2, 1))

print("\nГенерация случайных байтов (16 байт):", np.random.bytes(16))
print("\nГенерация случайных байтов (новый API):", rng.bytes(10))

# Демонстрация различных распределений
print("\n\n" + "="*50)
print("\nДЕМОНСТРАЦИЯ РАЗЛИЧНЫХ РАСПРЕДЕЛЕНИЙ:")
print("\nНормальное распределение (μ=0, σ=1), 5 чисел:", np.random.normal(0, 1, 5))
print("\nРавномерное распределение [0, 10), 5 чисел:", np.random.uniform(0, 10, 5))
print("\nБиномиальное распределение (n=10, p=0.7), 5 чисел:", np.random.binomial(10, 0.7, 5))
print("\nПуассоновское распределение (λ=4), 5 чисел:", np.random.poisson(4, 5))


Генерация случайного числа от 0 до 1: 0.18485445552552704

Генерация случайного числа от 0 до 1 (новый API): 0.8896014911107375

Массив 3x3 случайных чисел от 0 до 1:
 [[0.96958463 0.77513282 0.93949894]
 [0.89482735 0.59789998 0.92187424]
 [0.0884925  0.19598286 0.04522729]]

Массив 2x4 случайных чисел от 0 до 1 (новый API):
 [[0.65042471 0.53186476 0.19580054 0.22589953]
 [0.89572962 0.50101489 0.26719446 0.77611609]]

Случайное целое число от 0 до 10: 7

Массив из 5 целых чисел от 1 до 100:
 [85 80 82 53 24]

Матрица 2x3 целых чисел от 5 до 50:
 [[30 29 49]
 [45 33 19]]

Целое число от 0 до 10 (новый API): 4

Массив из 6 целых чисел от 1 до 100 (новый API):
 [ 2 58 89 73 33 22]

Выбор из списка ['A', 'B', 'C', 'D']: A

Выбор 3 элементов из списка с возвратом: ['X' 'X' 'Z']

Выбор 3 элементов из списка без возврата: ['Z' 'Y' 'X']

Выбор из списка с заданными вероятностями: ['Lose' 'Win' 'Win' 'Win' 'Lose']

Случайное число из нормального распределения (μ=0, σ=1): 0.4760425874269718



### Работа с массивами

In [46]:
# Создадим массивы для примеров
a = np.array([1, 0, 2, 0, 3, 0])
b = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
c = np.array([True, False, True, False])

print("Исходный массив a:", a)
print("\nИндексы ненулевых элементов a - np.nonzero(a):", np.nonzero(a))
print("Ненулевые элементы a - a[np.nonzero(a)]:", a[np.nonzero(a)])
print("Количество ненулевых элементов a - np.count_nonzero(a):", np.count_nonzero(a))

print("\nМассив b:\n", b)
print("Индексы ненулевых элементов b - np.nonzero(b):", np.nonzero(b))
print("Форма результата nonzero для 2D - np.array(np.nonzero(b)).T:\n", np.array(np.nonzero(b)).T)

print("\nЛогический массив c:", c)
print("Индексы True элементов c - np.flatnonzero(c):", np.flatnonzero(c))
print("Первый индекс True в c - np.argmax(c):", np.argmax(c))

d = np.array([3, 1, 4, 1, 5, 9])
print("\nМассив d:", d)
print("Индекс максимального элемента d - np.argmax(d):", np.argmax(d))
print("Индекс минимального элемента d - np.argmin(d):", np.argmin(d))
print("Максимальный элемент d - np.max(d):", np.max(d))
print("Минимальный элемент d - np.min(d):", np.min(d))

e = np.array([[1, 5, 3], [9, 2, 7]])
print("\nМатрица e:\n", e)
print("Индекс максимума в flattened e - np.argmax(e):", np.argmax(e))
print("Индексы максимумов по axis=0 - np.argmax(e, axis=0):", np.argmax(e, axis=0))
print("Индексы максимумов по axis=1 - np.argmax(e, axis=1):", np.argmax(e, axis=1))

f = np.array([1, 2, 3, 4, 5])
print("\nМассив f:", f)
print("Индекс первого элемента >2 - np.argwhere(f > 2)[0, 0]:", np.argwhere(f > 2)[0, 0])
print("Все индексы элементов >2 - np.argwhere(f > 2):", np.argwhere(f > 2))

g = np.array([[1, 0, 3], [0, 5, 0], [7, 0, 9]])
print("\nМатрица g:\n", g)
print("Индексы ненулевых элементов g - np.argwhere(g != 0):", np.argwhere(g != 0))
print("Значения ненулевых элементов g - g[np.nonzero(g)]:", g[np.nonzero(g)])

h = np.array([0, 0, 0, 1, 0, 0, 1, 0])
print("\nМассив h:", h)
print("Все индексы где h == 1 - np.where(h == 1)[0]:", np.where(h == 1)[0])
print("Первый индекс где h == 1 - np.where(h == 1)[0][0]:", np.where(h == 1)[0][0])

i = np.array([10, 20, 30, 40, 50])
print("\nМассив i:", i)
print("Элементы i > 25 - i[i > 25]:", i[i > 25])
print("Индексы элементов i > 25 - np.where(i > 25)[0]:", np.where(i > 25)[0])

j = np.array([1, 0, 0, 1, 1, 0, 1])
print("\nМассив j:", j)
print("Индексы перехода 0→1 - np.where((j[:-1] == 0) & (j[1:] == 1))[0] + 1:", np.where((j[:-1] == 0) & (j[1:] == 1))[0] + 1)
print("Индексы перехода 1→0 - np.where((j[:-1] == 1) & (j[1:] == 0))[0] + 1:", np.where((j[:-1] == 1) & (j[1:] == 0))[0] + 1)

k = np.array([False, True, False, True, True, False])
print("\nЛогический массив k:", k)
print("Индексы True в k - np.flatnonzero(k):", np.flatnonzero(k))
print("Количество True в k - np.count_nonzero(k):", np.count_nonzero(k))

l = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
print("\nМатрица l:\n", l)
print("Координаты единиц в l - np.argwhere(l == 1):", np.argwhere(l == 1))
print("Строки с единицами - np.nonzero(l)[0]:", np.nonzero(l)[0])
print("Столбцы с единицами - np.nonzero(l)[1]:", np.nonzero(l)[1])

m = np.array([5, 3, 8, 2, 7])
print("\nМассив m:", m)
print("Индексы отсортированного m - np.argsort(m):", np.argsort(m))
print("Отсортированный m - np.sort(m):", np.sort(m))
print("Три наибольших элемента m - m[np.argpartition(m, -3)[-3:]]:", m[np.argpartition(m, -3)[-3:]])

# Практический пример - поиск пиков в данных
data = np.array([1, 3, 7, 1, 2, 6, 0, 1])
print("\nДанные с пиками:", data)
peaks = np.where((data > np.roll(data, 1)) & (data > np.roll(data, -1)))[0]
print("Индексы пиков в данных - np.where((data > np.roll(data, 1)) & (data > np.roll(data, -1)))[0]:", peaks)
print("Значения пиков - data[peaks]:", data[peaks])

Исходный массив a: [1 0 2 0 3 0]

Индексы ненулевых элементов a - np.nonzero(a): (array([0, 2, 4]),)
Ненулевые элементы a - a[np.nonzero(a)]: [1 2 3]
Количество ненулевых элементов a - np.count_nonzero(a): 3

Массив b:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Индексы ненулевых элементов b - np.nonzero(b): (array([0, 1, 2]), array([0, 1, 2]))
Форма результата nonzero для 2D - np.array(np.nonzero(b)).T:
 [[0 0]
 [1 1]
 [2 2]]

Логический массив c: [ True False  True False]
Индексы True элементов c - np.flatnonzero(c): [0 2]
Первый индекс True в c - np.argmax(c): 0

Массив d: [3 1 4 1 5 9]
Индекс максимального элемента d - np.argmax(d): 5
Индекс минимального элемента d - np.argmin(d): 1
Максимальный элемент d - np.max(d): 9
Минимальный элемент d - np.min(d): 1

Матрица e:
 [[1 5 3]
 [9 2 7]]
Индекс максимума в flattened e - np.argmax(e): 3
Индексы максимумов по axis=0 - np.argmax(e, axis=0): [1 0 1]
Индексы максимумов по axis=1 - np.argmax(e, axis=1): [1 0]

Массив f: [1 2 3 4 5]
Индекс первого элеме

In [21]:
# массив-скаляр
s =  np.array(5)
print("Скаляр S:", s)

print("shape:", s.shape, "| ndim:", s.ndim, "| dtype:", s.dtype, "| nbytes:", s.nbytes)

Скаляр S: 5
shape: () | ndim: 0 | dtype: int64 | nbytes: 8


In [29]:
a = np.zeros(10)
print("Вектор a = ", a)

Вектор a =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
print("shape:", a.shape, "| ndim:", a.ndim, "| dtype:", a.dtype, "| nbytes:", a.nbytes)

shape: (10,) | ndim: 1 | dtype: float64 | nbytes: 80


In [26]:
a = np.arange(10,50) # вектор от 10 до 49
print("Вектор a=", a)

Вектор a= [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
print("shape:", a.shape, "| ndim:", a.ndim, "| dtype:", a.dtype, "| nbytes:", a.nbytes, "| size:", a.size)

shape: (40,) | ndim: 1 | dtype: int64 | nbytes: 320 | size: 40


In [35]:
A = np.arange(9).reshape(3,3)
print("Матрица (3х3)=\n", A)

Матрица (3х3)=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
print("shape:", A.shape, "| ndim:", A.ndim, "| dtype:", A.dtype, "| nbytes:", A.nbytes, "| size:", A.size)

shape: (3, 3) | ndim: 2 | dtype: int64 | nbytes: 72 | size: 9


In [36]:
a = np.array([1, 2, 0, 0, 4, 0])
idx = np.nonzero(a)
print("Индексы ненулевых элементов:", idx)

Индексы ненулевых элементов: (array([0, 1, 4]),)


In [39]:
a = np.random.rand( 3, 3, 3)
print("Массив (3х3х3):", a)

Массив (3х3х3): [[[0.18485446 0.96958463 0.77513282]
  [0.93949894 0.89482735 0.59789998]
  [0.92187424 0.0884925  0.19598286]]

 [[0.04522729 0.32533033 0.38867729]
  [0.27134903 0.82873751 0.35675333]
  [0.28093451 0.54269608 0.14092422]]

 [[0.80219698 0.07455064 0.98688694]
  [0.77224477 0.19871568 0.00552212]
  [0.81546143 0.70685734 0.72900717]]]


In [40]:
print("shape:", a.shape, "| ndim:", a.ndim, "| dtype:", a.dtype, "| nbytes:", a.nbytes, "| size:", a.size)

shape: (3, 3, 3) | ndim: 3 | dtype: float64 | nbytes: 216 | size: 27


In [41]:
a = np.random.rand( 10, 10)
print("Массив (10х10):", a)
print("shape:", a.shape, "| ndim:", a.ndim, "| dtype:", a.dtype, "| nbytes:", a.nbytes, "| size:", a.size)

Массив (10х10): [[0.77127035 0.07404465 0.35846573 0.11586906 0.86310343 0.62329813
  0.33089802 0.06355835 0.31098232 0.32518332]
 [0.72960618 0.63755747 0.88721274 0.47221493 0.11959425 0.71324479
  0.76078505 0.5612772  0.77096718 0.4937956 ]
 [0.52273283 0.42754102 0.02541913 0.10789143 0.03142919 0.63641041
  0.31435598 0.50857069 0.90756647 0.24929223]
 [0.41038292 0.75555114 0.22879817 0.07697991 0.28975145 0.16122129
  0.92969765 0.80812038 0.63340376 0.87146059]
 [0.80367208 0.18657006 0.892559   0.53934224 0.80744016 0.8960913
  0.31800347 0.11005192 0.22793516 0.42710779]
 [0.81801477 0.86073058 0.00695213 0.5107473  0.417411   0.22210781
  0.11986537 0.33761517 0.9429097  0.32320293]
 [0.51879062 0.70301896 0.3636296  0.97178208 0.96244729 0.2517823
  0.49724851 0.30087831 0.28484049 0.03688695]
 [0.60956433 0.50267902 0.05147875 0.27864646 0.90826589 0.23956189
  0.14489487 0.48945276 0.98565045 0.24205527]
 [0.67213555 0.76161962 0.23763754 0.72821635 0.36778313 0.6323058

In [42]:
print("Минимальное значение:", np.min(a))

Минимальное значение: 0.006952130531190703


In [43]:
print("Максимальное значение:", np.max(a))

Максимальное значение: 0.9856504541106007


In [54]:
a = np.random.rand(30)
print("Вектор а:", a)

Вектор а: [0.72609133 0.97585208 0.51630035 0.32295647 0.79518619 0.27083225
 0.43897142 0.07845638 0.02535074 0.96264841 0.83598012 0.69597421
 0.40895294 0.17329432 0.15643704 0.2502429  0.54922666 0.71459592
 0.66019738 0.2799339  0.95486528 0.73789692 0.55435405 0.61172075
 0.41960006 0.24773099 0.35597268 0.75784611 0.01439349 0.11607264]


In [55]:
mean = np.mean(a)
print("Среднее значение:", mean)

Среднее значение: 0.48693113332940735


In [62]:
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [63]:
a[1:-1, 1:-1] = 0
print("Массив 5х5 с единицами по границе и нулями внутри:\n", a)

Массив 5х5 с единицами по границе и нулями внутри:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
idx = np.unravel_index(99, (6, 7, 8))
print("Индекс 100-го элемента:", idx)                                             # Стандартный вывод
print("Индекс 100-го элемента:", tuple(int(i) for i in idx))                      # Преобразование в tuple с int
print("Индекс 100-го элемента:", tuple(map(int, idx)))                            # Использование map
i, j, k = map(int, idx)                                                          
print("Индекс 100-го элемента:", (i, j, k))                                       # Распаковка с преобразованием
print("Индекс 100-го элемента: (%d, %d, %d)" % idx)                               # Форматирование строки
print(f"Индекс 100-го элемента: ({int(idx[0])}, {int(idx[1])}, {int(idx[2])})")   # f-strings с явным преобразованием

Индекс 100-го элемента: (np.int64(1), np.int64(5), np.int64(3))
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)
Индекс 100-го элемента: (1, 5, 3)


In [75]:
a = np.ones((6, 7, 8))
a[1:-1, 1:-1, 1:-1] = 0
a

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.,

In [81]:
# Матрица A 5х3
A = np.random.rand(5, 3)

# Матрица B 3х2
B = np.random.rand(3, 2)
print("A\n",A,"\nB\n",B)

# Произведение матриц A x B
print("\nA x B - np.dot(A, B):\n", np.dot(A, B))

A
 [[0.08134878 0.08483771 0.98663958]
 [0.3742708  0.37064215 0.81279957]
 [0.94724858 0.98600106 0.75337819]
 [0.37625959 0.08350072 0.77714692]
 [0.55840425 0.42422201 0.90635439]] 
B
 [[0.11119748 0.4926251 ]
 [0.01135364 0.46866064]
 [0.05630328 0.11881792]]

A x B - np.dot(A, B):
 [[0.06556004 0.19706501]
 [0.09158939 0.45465573]
 [0.15894402 1.01825315]
 [0.08654307 0.31682739]
 [0.11794033 0.58159125]]
