In [1]:
import numpy as np

# создадим нулевой вектор размера 10
v_one = np.zeros((10))  
print(v_one)

# узнаем объем памяти созданного ранее массива (нулевого вектора)
print(f"Массив занимает {v_one.nbytes} байт")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Массив занимает 80 байт


In [2]:
# Создадим вектор от 10 до 49
vect = np.arange(10, 50)
print(f"Вектор от 10 до 49 {vect}")

Вектор от 10 до 49 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# типовые конструкции
a = [1,2,3, 'fff', [], 'aaa'] #список
b = (1,2,3) #кортеж
c = {"key_1": [1,2,3]}  #словарь

In [4]:
# из вектора vect создадим обратный вектор с помощью слайсинга
r_vect = vect[::-1]
print(f"Обратный вектор вектора vect:\n {r_vect}")

Обратный вектор вектора vect:
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [5]:
# Найти ненулевые элементы из массива
M = [1 ,2, 0, 0, 4, 0]
non_zero = list(filter(lambda x: x != 0, M))
print(non_zero)
print(M[M != 0])
non_zero2 = M[M != 0]
nonzero_index = np.nonzero(M)
print(nonzero_index)



[1, 2, 4]
2
(array([0, 1, 4]),)


In [6]:
# Создание массива 3x3x3 со случайными значениями
arr = np.random.random((3, 3, 3))
print(f"Массив 3x3x3 со случайными значениями:\n {np.random.rand(3, 3, 3)}") 

Массив 3x3x3 со случайными значениями:
 [[[0.56590925 0.46962398 0.25643291]
  [0.06091037 0.78806412 0.18830074]
  [0.14085326 0.8242122  0.06362572]]

 [[0.93849688 0.77410548 0.93381921]
  [0.65856635 0.97509208 0.65627387]
  [0.37587483 0.08201012 0.14375154]]

 [[0.35320706 0.34888708 0.42007024]
  [0.80390933 0.80598434 0.19391986]
  [0.56395147 0.56132312 0.17914622]]]


In [7]:
# Создадим массив 10х10 и найдем минимум и максимум
arr = np.random.rand(10, 10)
print("Min ",np.min(arr),"\nMax ",np.max(arr))
print("Min ", arr.min(),"\nMax ", arr.max())

Min  0.0001281696621101558 
Max  0.9877028269463434
Min  0.0001281696621101558 
Max  0.9877028269463434


In [8]:
# Создадим случайный вектор размера 30 и найдем среднее значение

v = np.random.rand(30)
print("AVG =", np.mean(v))
print(f'AVG = {np.mean(v):.4f}')

AVG = 0.6743598144319767
AVG = 0.6744


In [9]:
# Создадим 2d массив с 1 на границе и нулем внутри
# Создаем массив 3x3 с единицами
ones = np.ones((3, 3), dtype=int)
ones
# Заполняем центр нулем с помощью среза
ones[1:-1, 1:-1] = 0  
ones

print("Массив 3x3 с 1 на границе и 0 в центре:")
M = np.ones((3, 3), dtype=int)
M[1:2, 1:2] = 0 
print(M)



Массив 3x3 с 1 на границе и 0 в центре:
[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [10]:
# создадим 1d массив со случайными значениями от 1 до 10
# инвертируем все элементы со значениями 3 и 8
# Создаем 1D массив со случайными значениями от 1 до 10
R = np.random.randint(1, 11, size=10)
print("Исходный массив:\n",R)
# Инвертируем элементы со значениями 3 и 8
# Создаем маску для элементов 3 и 8
mask = (R == 3) | (R == 8)
# Инвертируем: 3 -> 8, 8 -> 3
#R[mask] = np.where(R[mask] == 3, 8, 3)

вот так же тоже можно в предыдущей задаче?
R = np.random.randint(1, 11, 10)
mask = (R == 3) | (R == 8)
R[mask] = np.where(R[mask] == 3, 8, 3)

mask3 = (R == 3)
mask8 = (R == 8)
R[mask3] = 8
R[mask8] = 3

print("Массив после инвертирования 3 и 8:\n",R)

Исходный массив:
 [ 3  3  9  9  3  5  4  2  4 10]
Object `задаче` not found.
Массив после инвертирования 3 и 8:
 [10  1  7  5  6  9  2  8  2  3]


In [20]:
# 1- [1, 2, 3, 4, 5]
# 2- [3, 4, 5, 6, 7]
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
common_val = np.intersect1d(a, b)
print(common_val)

[3 4 5]


In [17]:
# Создадим матрицу 5х5 со значением строк от 0 до 4
print(np.random.randint(0, 5, 25).reshape(5,5))

a = np.arange(5)
a 
a_x_5 = np.tile(a, (5, 1))
a_x_5

[[1 2 1 4 0]
 [4 4 3 4 2]
 [4 0 4 4 1]
 [2 1 3 1 3]
 [3 3 3 0 0]]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [21]:
# Создадим вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0
print(np.random.uniform(0, 1, 10))

[0.54417455 0.12284404 0.9466664  0.54358187 0.05051168 0.63948292
 0.15006411 0.57612952 0.23605113 0.21075013]
