In [2]:
import numpy as np

# Создание из списка + явный тип
x = np.array([1, 2, 3], dtype=np.int32)
print("x =", x, "| dtype:", x.dtype)

x = [1 2 3] | dtype: int32


In [3]:
# Последовательности чисел
A = np.arange(6)              # 0,1,2,3,4,5
print("A =", A)

B = np.linspace(0.0, 1.0, 5)  # 5 точек от 0 до 1 включительно
print("B =", B)

A = [0 1 2 3 4 5]
B = [0.   0.25 0.5  0.75 1.  ]


In [4]:
# Матрицы-заготовки
Z = np.zeros((2, 3))          # все нули
O = np.ones((2, 3))           # все единицы
F = np.full((2, 3), 7)        # все семёрки
I = np.eye(3)                 # единичная матрица 3x3
print("Z:\n", Z)
print("O:\n", O)
print("F:\n", F)
print("I:\n", I)

Z:
 [[0. 0. 0.]
 [0. 0. 0.]]
O:
 [[1. 1. 1.]
 [1. 1. 1.]]
F:
 [[7 7 7]
 [7 7 7]]
I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Базовые свойства формы и размера
M = np.arange(12).reshape(3, 4)   # меняем форму без копии данных
print("M:\n", M)
print("shape:", M.shape, "| ndim:", M.ndim, "| size:", M.size, "| dtype:", M.dtype)

M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4) | ndim: 2 | size: 12 | dtype: int64


In [6]:
# Преобразование типа (создаёт копию)
M32 = M.astype(np.float32)
print("M32 dtype:", M32.dtype)


M32 dtype: float32


In [7]:
# Автоматический размер в reshape через -1 (подбирается NumPy)
R = np.arange(8).reshape(2, -1)   # -1 => автоматически 4 столбца
print("R:\n", R, "| shape:", R.shape)

R:
 [[0 1 2 3]
 [4 5 6 7]] | shape: (2, 4)


In [9]:
A = np.arange(12).reshape(3, 4)
print("A:\n", A)

# Доступ к элементу по индексу (строка, столбец)
print("A[1, 2] =", A[1, 2])   # элемент во 2-й строке, 3-м столбце

# Срезы (slice) по строкам и столбцам
print("A[0, :] =", A[0, :])   # вся первая строка
print("A[:, 1] =", A[:, 1])   # весь второй столбец

# Подмассив срезом
S = A[0:2, 1:3]
print("S:\n", S)

# Изменение через срез отражается в исходном массиве
S[0, 0] = -1
print("После изменения S:\n", A)

A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A[1, 2] = 6
A[0, :] = [0 1 2 3]
A[:, 1] = [1 5 9]
S:
 [[1 2]
 [5 6]]
После изменения S:
 [[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
A = np.arange(12).reshape(3, 4)
print("A:\n", A)

# Булева маска: True для чётных элементов
mask = (A % 2 == 0)
print("Маска:\n", mask)

# Применение маски
E = A[mask]
print("Чётные элементы:", E)

# Булева маска для диапазона значений
mask2 = (A > 3) & (A < 10)
print("Маска (A > 3 и A < 10):\n", mask2)

F = A[mask2]
print("Элементы от 4 до 9:", F)


A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Маска:
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
Чётные элементы: [ 0  2  4  6  8 10]
Маска (A > 3 и A < 10):
 [[False False False False]
 [ True  True  True  True]
 [ True  True False False]]
Элементы от 4 до 9: [4 5 6 7 8 9]


In [11]:
A = np.arange(12).reshape(3, 4)
print("A:\n", A)

# Выбор целых строк
rows = [0, 2]
R = A[rows]
print("Строки 0 и 2:\n", R)

# Выбор элементов по координатам
rows = np.array([0, 2])
cols = np.array([1, 3])
F = A[rows[:, None], cols]
print("Элементы по координатам:\n", F)

# Перестановка столбцов
P = A[:, [2, 0, 3, 1]]
print("Столбцы в новом порядке:\n", P)


A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Строки 0 и 2:
 [[ 0  1  2  3]
 [ 8  9 10 11]]
Элементы по координатам:
 [[ 1  3]
 [ 9 11]]
Столбцы в новом порядке:
 [[ 2  0  3  1]
 [ 6  4  7  5]
 [10  8 11  9]]


In [12]:
x = np.array([1, 4, 9, 16])
print("x:", x)

# Унарные ufunc (один массив на входе)
y = np.sqrt(x)              # квадратный корень
print("sqrt(x):", y)

z = np.exp(x)               # экспонента
print("exp(x):", z)

# Бинарные ufunc (два массива на входе)
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = np.add(a, b)            # сложение
print("a + b:", c)

d = np.multiply(a, b)       # умножение
print("a * b:", d)


x: [ 1  4  9 16]
sqrt(x): [1. 2. 3. 4.]
exp(x): [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
a + b: [11 22 33 44]
a * b: [ 10  40  90 160]


In [13]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("A:\n", A)

# Основные статистики
print("Сумма всех элементов:", np.sum(A))
print("Минимум:", np.min(A))
print("Максимум:", np.max(A))
print("Среднее:", np.mean(A))
print("Стандартное отклонение:", np.std(A))

# Статистики по осям
print("Сумма по строкам:", np.sum(A, axis=1))
print("Сумма по столбцам:", np.sum(A, axis=0))
print("Среднее по столбцам:", np.mean(A, axis=0))


A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Сумма всех элементов: 45
Минимум: 1
Максимум: 9
Среднее: 5.0
Стандартное отклонение: 2.581988897471611
Сумма по строкам: [ 6 15 24]
Сумма по столбцам: [12 15 18]
Среднее по столбцам: [4. 5. 6.]


In [14]:
# Два вектора
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Скалярное произведение
dot = np.dot(u, v)
print("Скалярное произведение u·v:", dot)

# Матрицы
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Матричное умножение
C = np.matmul(A, B)   # или A @ B
print("A @ B:\n", C)

# Определитель
det = np.linalg.det(A)
print("det(A) =", det)

# Обратная матрица
invA = np.linalg.inv(A)
print("A^(-1):\n", invA)

# Решение системы Ax = b
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Решение системы Ax = b:", x)


Скалярное произведение u·v: 32
A @ B:
 [[19 22]
 [43 50]]
det(A) = -2.0000000000000004
A^(-1):
 [[-2.   1. ]
 [ 1.5 -0.5]]
Решение системы Ax = b: [0.  0.5]


In [15]:
# Случайные целые числа
r1 = np.random.randint(0, 10, size=5)
print("Случайные целые от 0 до 9:", r1)

# Равномерное распределение [0, 1)
r2 = np.random.rand(3, 2)
print("Равномерное распределение:\n", r2)

# Нормальное распределение (среднее=0, σ=1)
r3 = np.random.randn(3, 3)
print("Нормальное распределение:\n", r3)

# Фиксируем зерно для воспроизводимости
np.random.seed(42)
r4 = np.random.randint(0, 100, size=5)
print("Повторяемый результат:", r4)


Случайные целые от 0 до 9: [9 7 6 0 2]
Равномерное распределение:
 [[0.08962477 0.05311266]
 [0.38081356 0.72491985]
 [0.85285705 0.16484031]]
Нормальное распределение:
 [[-1.49894038  0.66244764 -0.36987461]
 [ 0.24216777  0.6035533   0.96342139]
 [ 0.74820731 -0.77221251 -1.40376046]]
Повторяемый результат: [51 92 14 71 60]
