In [15]:
import numpy as np

In [16]:
# Поэлементная формула без цикла
x = np.arange(-3, 4)           # [-3, -2, ..., 3], shape (7,)
y_loop = [2*t + 1 for t in x]  # циклом
y_vec  = 2*x + 1               # векторно, за раз

print("\nсовпадает ли результат:", np.array_equal(y_vec, np.array(y_loop)))
print("x.shape:", x.shape, "| y_vec.shape:", y_vec.shape)

# Преобразование всей матрицы (C->F) одной формулой
C = np.array([[0, 10, 20],
              [5, 15, 25]])    # градусы Цельсия, shape (2, 3)
F = C * 9/5 + 32               # поэлементно: (C · 9/5) + 32

print("\n\nF:\n", F)
print("\nC.shape:", C.shape, "| F.shape:", F.shape)



совпадает ли результат: True
x.shape: (7,) | y_vec.shape: (7,)


F:
 [[32. 50. 68.]
 [41. 59. 77.]]

C.shape: (2, 3) | F.shape: (2, 3)


In [17]:
# все попарные суммы двух векторов (broadcasting)
a = np.array([1, 2, 3])        # shape (3,)
b = np.array([10, 20, 30, 40]) # shape (4,)
S = a[:, None] + b             # (3,1) + (4,) -> (3,4)

print("\n\nS.shape:", S.shape)
print("S (пример 2×3 блока):\n", S[:2, :3])



S.shape: (3, 4)
S (пример 2×3 блока):
 [[11 21 31]
 [12 22 32]]


In [19]:
# Исходная матрица 3 строки × 4 столбца
M = np.arange(12).reshape(3, 4)
print("M:\n", M)
print("M.shape:", M.shape)  # (3, 4)

# Добавляем вектор-строку ко всем строкам (совместимо по последней оси)
r = np.array([10, 20, 30, 40])      # shape (4,)
R = M + r                           # (3,4) + (4,) -> (3,4)
print("\nr.shape:", r.shape, "| R.shape:", R.shape)
print("Первые 2 строки R:\n", R[:2])

# Добавляем вектор-столбец (нужно добавить ось)
c = np.array([100, 200, 300])       # shape (3,)
try:
    _ = M + c                        # (3,4) + (3,) -> ОШИБКА: 4 != 3 по последней оси
except ValueError as e:
    print("\nожидаемая ошибка без оси:", e)

C = M + c[:, None]                  # (3,1) + (3,4) -> (3,4)
print(" c[:, None].shape:", (c[:, None]).shape, "| результат:", C.shape)
print("Первые 2 столбца C:\n", C[:, :2])

M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
M.shape: (3, 4)

r.shape: (4,) | R.shape: (3, 4)
Первые 2 строки R:
 [[10 21 32 43]
 [14 25 36 47]]

ожидаемая ошибка без оси: operands could not be broadcast together with shapes (3,4) (3,) 
 c[:, None].shape: (3, 1) | результат: (3, 4)
Первые 2 столбца C:
 [[100 101]
 [204 205]
 [308 309]]


In [21]:
# Центрирование по столбцам vs по строкам (mean + keepdims)
col_centered = M - M.mean(axis=0, keepdims=True)  # форма средних (1,4) -> вычитается из каждой строки
row_centered = M - M.mean(axis=1, keepdims=True)  # форма средних (3,1) -> вычитается из каждого столбца
print("col_centered.shape:", col_centered.shape, "| row_centered.shape:", row_centered.shape)
print("col_centered (фрагмент 2×2):\n", np.round(col_centered[:2, :2], 2))

# Внешнее (попарное) произведение без двойного цикла
a = np.array([1, 2, 3])             # (3,)
b = np.array([10, 20, 30, 40])      # (4,)
Outer = a[:, None] * b[None, :]     # (3,1) * (1,4) -> (3,4)
print("\nOuter.shape:", Outer.shape)
print("Outer (фрагмент 2×3):\n", Outer[:2, :3])


col_centered.shape: (3, 4) | row_centered.shape: (3, 4)
col_centered (фрагмент 2×2):
 [[-4. -4.]
 [ 0.  0.]]

Outer.shape: (3, 4)
Outer (фрагмент 2×3):
 [[10 20 30]
 [20 40 60]]


In [22]:
# Исходный вектор из 12 элементов
x = np.arange(12)                    # shape (12,)
print("x.shape:", x.shape)

# reshape к матрице 3×4 (без изменения данных)
A = x.reshape(3, 4)                  # shape (3, 4)
print("A.shape:", A.shape)

# Автовывод размера с -1
B = x.reshape(-1, 6)                 # 12 элементов -> (2, 6)
print("\n\nB.shape (ожидаем 2×6):", B.shape)

x.shape: (12,)
A.shape: (3, 4)


B.shape (ожидаем 2×6): (2, 6)


In [23]:
# Добавление оси: «строка» и «столбец»
row = x[None, :]                     # shape (1, 12) — вектор-строка
col = x[:, None]                     # shape (12, 1) — вектор-столбец
print("row.shape:", row.shape, "| col.shape:", col.shape)

# Сглаживание: ravel (view) vs flatten (copy)
r = A.ravel()                        # по возможности представление (view)
f = A.flatten()                      # всегда копия
print("\n\nr.shape:", r.shape, "| f.shape:", f.shape)
print("shares_memory(A, r):", np.shares_memory(A, r))  # True -> представление
print("shares_memory(A, f):", np.shares_memory(A, f))  # False -> копия


row.shape: (1, 12) | col.shape: (12, 1)


r.shape: (12,) | f.shape: (12,)
shares_memory(A, r): True
shares_memory(A, f): False


In [25]:
# Исходный вектор
x = np.array([-3, -1, 0, 1, 2, 3])
print("x:", x, "| shape:", x.shape)

# Простая маска и отбор элементов
mask_pos = x > 0                       # поэлементно: True там, где x > 0
pos = x[mask_pos]                      # чтение по маске -> новый массив
print("\nmask_pos:", mask_pos, "| dtype:", mask_pos.dtype, "| shape:", mask_pos.shape)
print("отобраны положительные:", pos, "| count:", np.count_nonzero(mask_pos))

# Комбинирование условий: чётные и положительные
mask_even_pos = ((x % 2) == 0) & (x > 0)  # скобки обязательны при & и |
print("\n\nmask_even_pos:", mask_even_pos)
print("\чётные положительные:", x[mask_even_pos])

x: [-3 -1  0  1  2  3] | shape: (6,)

mask_pos: [False False False  True  True  True] | dtype: bool | shape: (6,)
отобраны положительные: [1 2 3] | count: 3


mask_even_pos: [False False False False  True False]
\чётные положительные: [2]


In [26]:
# Маска на матрице + изменение по месту
M = np.arange(-6, 6).reshape(3, 4)     # матрица 3×4: от -6 до 5
mask_neg = M < 0
print("\nM (до):\n", M)
M[mask_neg] = 0                        # присваивание по маске меняет исходный M
print("\nM (после, отрицательные->0):\n", M)

# Условное преобразование с np.where (векторный if)
# если x >= 0 -> x**2, иначе -> -1
y = np.where(x >= 0, x**2, -1)
print("\n\n np.where результат:", y, "| shape:", y.shape)



M (до):
 [[-6 -5 -4 -3]
 [-2 -1  0  1]
 [ 2  3  4  5]]

M (после, отрицательные->0):
 [[0 0 0 0]
 [0 0 0 1]
 [2 3 4 5]]


 np.where результат: [-1 -1  0  1  4  9] | shape: (6,)
